#!/usr/bin/env bash
#install and configure HAProxy on lb-01 server

sudo apt-get -y update
apt-get -y install haproxy


server_config=\
"
frontend  ayo-frontend
        bind *:80
        mode http
        default_backend amine-backend
backend ayo-backend
        balance roundrobin
        server 438453-web-01 54.242.162.229  check
        server 438453-web-02 100.25.0.196 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
