#!/usr/bin/env bash
#exist
if [ -e "school" ]
then
        echo $"school file exists"
        #empty
        if [ -s "school" ]
        then
                echo $"school file is not empty"
        #not empty
        else
                echo $"school file is empty"
        fi
        #regular
        if [ -f "school" ]
        then
                echo $"school is a regular file"
        fi
#not exist
else
        echo $"school file does not exist"
fi
